# Generated by Django 4.0.4 on 2022-04-20 13:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calenders',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('token_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=300, null=True)),
                ('name', models.CharField(max_length=300)),
                ('X1', models.CharField(blank=True, max_length=200, null=True)),
                ('X2', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('token_file', models.FileField(blank=True, null=True, upload_to='json_files')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('days_to_look', models.IntegerField(null=True)),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thur'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], max_length=56, null=True)),
                ('event_duration_type', models.CharField(choices=[('Minute', 'minute'), ('Day', 'day'), ('Hour', 'hour')], max_length=100)),
                ('event_duration', models.IntegerField()),
                ('snooze_type', models.CharField(choices=[('Minute', 'minute'), ('Day', 'day'), ('Hour', 'hour')], max_length=100)),
                ('snooze_duration', models.IntegerField()),
                ('calenders', models.ManyToManyField(to='cal.calenders')),
                ('filter', models.ManyToManyField(to='cal.filter')),
            ],
        ),
    ]
