# Generated by Django 4.0.4 on 2022-04-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_calenders_ide_alter_calenders_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calenders',
            options={'verbose_name_plural': 'Calenders'},
        ),
        migrations.AlterModelOptions(
            name='eventdetails',
            options={'verbose_name_plural': 'Event Details'},
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name_plural': 'FIlters'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name_plural': 'Tokens'},
        ),
    ]
