# Generated by Django 4.0.4 on 2022-04-23 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_alter_calenders_options_alter_eventdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calenders',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cal.calenders'),
        ),
    ]
