# Generated by Django 4.0.4 on 2022-04-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_calenders_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calenders',
            name='parent',
        ),
    ]
