# Generated by Django 4.0.4 on 2022-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_remove_calenders_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calenders',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
