# Generated by Django 4.0.4 on 2022-05-02 13:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_calenders_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='snooze_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thur'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], max_length=56, null=True),
        ),
    ]
