# Generated by Django 4.0.4 on 2022-05-03 11:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_eventdetails_snooze_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='snooze_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thur'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], max_length=56, null=True),
        ),
    ]
