# Generated by Django 4.0.4 on 2022-05-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_alter_eventdetails_snooze_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='X1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='value to set'),
        ),
    ]
