# Generated by Django 4.0.4 on 2022-05-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_alter_filter_x1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='name',
            new_name='keyword',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='detail',
        ),
        migrations.AddField(
            model_name='filter',
            name='filter_detail',
            field=models.CharField(max_length=300, null=True, verbose_name='Filter Detail'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='X1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='value to set(X1)'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='X2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='value to set(X2)'),
        ),
    ]
