# Generated by Django 4.0.4 on 2022-05-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_rename_name_filter_keyword_remove_filter_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='keyword',
            field=models.CharField(choices=[('Window', 'Window'), ('Temperature', 'Temperature'), ('Sunrise', 'Sunrise'), ('Sunset', 'Sunset'), ('Low Tide', 'Low Tide')], max_length=30),
        ),
    ]
