# Generated by Django 4.0.4 on 2022-05-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_alter_filter_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='apply_filter',
            field=models.BooleanField(default=True),
        ),
    ]
