# Generated by Django 4.0.4 on 2022-05-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_eventdetails_apply_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetails',
            old_name='apply_filter',
            new_name='apply_snooze',
        ),
    ]
