# Generated by Django 4.0.4 on 2022-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_rename_apply_filter_eventdetails_apply_snooze'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='Temperature_X1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Temperature value (X1)'),
        ),
        migrations.AddField(
            model_name='filter',
            name='Temperature_X2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Temperature value (X2)'),
        ),
        migrations.AddField(
            model_name='filter',
            name='add_temperature',
            field=models.BooleanField(default=False, verbose_name='Add Temperature?'),
        ),
    ]
