# Generated by Django 4.0.4 on 2022-05-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0014_filter_temperature_x1_filter_temperature_x2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='keyword',
            field=models.CharField(choices=[('Window', 'Window'), ('Sunrise', 'Sunrise'), ('Sunset', 'Sunset'), ('Low Tide', 'Low Tide')], max_length=30),
        ),
    ]
