# Generated by Django 4.0.4 on 2022-05-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0016_alter_filter_temperature_x1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='Temperature_X1',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature value (X1)'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='Temperature_X2',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature value (X2)'),
        ),
    ]
