# Generated by Django 4.0.4 on 2022-05-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0017_alter_filter_temperature_x1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='free_event',
            field=models.BooleanField(default=True, verbose_name='include free events?'),
        ),
    ]
