# Generated by Django 4.0.4 on 2022-05-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0018_eventdetails_free_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='Temperature_X1',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='Temperature_X2',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='add_temperature',
        ),
        migrations.AlterField(
            model_name='filter',
            name='keyword',
            field=models.CharField(choices=[('Window', 'Window'), ('Sunrise', 'Sunrise'), ('Sunset', 'Sunset'), ('Low Tide', 'Low Tide'), ('Temperature', 'Temperature')], max_length=30),
        ),
    ]
