# Generated by Django 4.0.4 on 2022-05-29 20:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0020_alter_filter_x1_alter_filter_x2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='apply_snooze',
            field=models.BooleanField(default=True, help_text='Apply snooze'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='calenders',
            field=models.ManyToManyField(help_text='Pick calendars to look into', to='cal.calenders'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thur'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], help_text='Days to look at', max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='days_to_look',
            field=models.IntegerField(help_text='Number of days to look', null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_duration',
            field=models.IntegerField(help_text='X2 should be greater than X1'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_duration_type',
            field=models.CharField(choices=[('Minute', 'minute'), ('Day', 'day'), ('Hour', 'hour')], help_text='Days / Hours / Minutes', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='filter',
            field=models.ManyToManyField(help_text='Choose Filter(s)', to='cal.filter'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='snooze_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thur'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], help_text='Snooze days (Optional)', max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='snooze_duration',
            field=models.IntegerField(help_text='Duration for the snooze'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='snooze_type',
            field=models.CharField(choices=[('Minute', 'minute'), ('Day', 'day'), ('Hour', 'hour')], help_text='Days / Hours / Minutes', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='title',
            field=models.CharField(help_text='Event Title', max_length=200),
        ),
    ]
