# Generated by Django 4.0.4 on 2022-06-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0021_alter_eventdetails_apply_snooze_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filter',
            name='X1',
            field=models.CharField(blank=True, help_text='if Window is selected Please use 12-hour clock and X2 should be greater than X1', max_length=200, null=True, verbose_name='value to set(X1)'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='X2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='value to set(X2)'),
        ),
    ]
